### ISSUE TITLE
Moving away from Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [aichbauer/pipefi#1]
There are [a few places](https://github.com/aichbauer/pipefi/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) in the repo where `new Buffer()` is being used. This is deprecated and unsafe. Do you think you could update those places to use `Buffer.from()`?

**Comment by aichbauer** [comment]
Hey @gabrielschulhof,

thanks for your issue. I read through the nodejs docs and see why we should update. Would you mind open a PR to fix this?

**Comment by gabrielschulhof** [comment]
Looks like somebody has already submitted a fix 🙂
https://github.com/aichbauer/pipefi/tree/fix/buffer

**Comment by JPeer264** [comment]
Closed in favor of #2
